apiVersion: v1
kind: Service
metadata:
  name: {{ include "projectapp.backend.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "projectapp.common.labels" . | nindent 4 }}
    {{- include "projectapp.backend.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "projectapp.backend.selectorLabels" . | nindent 4 }}